// Single file to include functionality of the Astro Core

#include "include/raylib.h"
#include "header/entity.h"
#include "header/input.h"
#include "header/animatedSpriteEntity.h"
#include "header/structs.h"
#include "header/scene.h"
#include "header/texturemanager.h"
#include "header/game.h"
#include "header/light2D.h"
#include "header/filemanager.h"
#include "header/tilemap.h"
#include "header/pixelPerfectCamera.h"
#include "header/cameraEntity.h"
#include "game.h"